/* Additional record code for Whole generated by the OpenModelica Compiler OpenModelica 1.12.0~7-g6d56dda. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SubPartState__desc_added 1
const char* SubPartState__desc__fields[2] = {"b","y"};
struct record_description SubPartState__desc = {
  "SubPartState", /* package_record__X */
  "SubPartState", /* package.record_X */
  SubPartState__desc__fields
};

#define PartState__desc_added 1
const char* PartState__desc__fields[4] = {"a","subPart","x","y"};
struct record_description PartState__desc = {
  "PartState", /* package_record__X */
  "PartState", /* package.record_X */
  PartState__desc__fields
};

#define SubPartState$partState$subPart__desc_added 1
const char* SubPartState$partState$subPart__desc__fields[2] = {"b","y"};
struct record_description SubPartState$partState$subPart__desc = {
  "SubPartState$partState$subPart", /* package_record__X */
  "SubPartState$partState$subPart", /* package.record_X */
  SubPartState$partState$subPart__desc__fields
};

#define PartState$partState__desc_added 1
const char* PartState$partState__desc__fields[4] = {"a","subPart","x","y"};
struct record_description PartState$partState__desc = {
  "PartState$partState", /* package_record__X */
  "PartState$partState", /* package.record_X */
  PartState$partState__desc__fields
};

#ifdef __cplusplus
}
#endif

