/* Simulation code for Whole generated by the OpenModelica Compiler OpenModelica 1.12.0~7-g6d56dda. */
#if !defined(Whole__MODEL_H)
#define Whole__MODEL_H
#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "Whole_functions.h"

#define PartState_index 0
#define PartState$partState_index 1
#define SubPartState_index 2
#define SubPartState$partState$subPart_index 3

extern void Whole_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Whole_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Whole_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Whole_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Whole_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Whole_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Whole_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Whole_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Whole_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Whole_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Whole_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Whole_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Whole_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern int Whole_checkForDiscreteChanges(DATA *data, threadData_t *threadData);
extern const char* Whole_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Whole_relationDescription(int i);
extern void Whole_function_initSample(DATA *data, threadData_t *threadData);
extern int Whole_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int Whole_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int Whole_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int Whole_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int Whole_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int Whole_functionJacG_column(void* data, threadData_t *threadData);
extern int Whole_functionJacA_column(void* data, threadData_t *threadData);
extern int Whole_functionJacB_column(void* data, threadData_t *threadData);
extern int Whole_functionJacC_column(void* data, threadData_t *threadData);
extern int Whole_functionJacD_column(void* data, threadData_t *threadData);
extern const char* Whole_linear_model_frame(void);
extern const char* Whole_linear_model_datarecovery_frame(void);
extern int Whole_mayer(DATA* data, modelica_real** res, short *);
extern int Whole_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Whole_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Whole_setInputData(DATA *data, const modelica_boolean file);
extern int Whole_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Whole_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Whole_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int Whole_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void Whole_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Whole_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Whole_inputNames(DATA* data, char ** names);
extern int Whole_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Whole_functionLocalKnownVars(DATA*, threadData_t*);
extern int Whole_symbolicInlineSystem(DATA*, threadData_t*);

#include "Whole_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#endif

